// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "202303050917164_Initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
